### ISSUE TITLE
[App Crash] : java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by deepakby1121** [pubnub/pubnub-android-chat#3]
Logs:

 FATAL EXCEPTION: Subscription Manager Consumer Thread
                                                                          Process: com.coffeeenterprise.test, PID: 18427
                                                                          java.util.ConcurrentModificationException
                                                                              at java.util.ArrayList$Itr.next(ArrayList.java:831)
                                                                              at com.pubnub.api.managers.ListenerManager.announce(ListenerManager.java:42)
                                                                              at com.pubnub.api.workers.SubscribeMessageWorker.processIncomingPayload(SubscribeMessageWorker.java:197)
                                                                              at com.pubnub.api.workers.SubscribeMessageWorker.takeMessage(SubscribeMessageWorker.java:60)
                                                                              at com.pubnub.api.workers.SubscribeMessageWorker.run(SubscribeMessageWorker.java:51)
                                                                              at java.lang.Thread.run(Thread.java:761)

**Comment by rs-bprakash** [comment]
A similar issue has occurred during the PubNub Access Manager (PAM) implementation. This is causing out-of-memory issues.
Did anyone face a similar issue recently?

Name: Subscription Manager Consumer Thread
State: WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@568c8501
Total blocked: 0  Total waited: 1
Stack trace: 
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
com.pubnub.api.workers.SubscribeMessageWorker.takeMessage(SubscribeMessageWorker.java:83)
com.pubnub.api.workers.SubscribeMessageWorker.run(SubscribeMessageWorker.java:74)
java.lang.Thread.run(Thread.java:748)
